export const teachers = [
  {
    id: "tb-joshua",
    name: "Prophet T.B. Joshua",
    ministry: "The Synagogue, Church Of All Nations",
    type: "Estate",
    status: "estate",
    relationship: "Estate - official sources only",
    image: "/assets/pastor_poju.jpg",
    topics: ["Faith", "Healing", "Prayer", "Hope"],
    officialSources: ["Official SCOAN channel", "SCOAN sermon library", "Emmanuel TV public routes"],
    canDeepRag: false,
  },
  {
    id: "pastor-chris",
    name: "Pastor Chris Oyakhilome",
    ministry: "LoveWorld Incorporated / Christ Embassy",
    type: "Living teacher",
    status: "unverified",
    relationship: "Not yet affiliated with Sayved",
    image: "/assets/pastor_mike.jpg",
    topics: ["Faith", "Confession", "Healing", "Prayer"],
    officialSources: ["LoveWorld official platforms", "Rhapsody public routes", "Official YouTube route"],
    canDeepRag: false,
  },
  {
    id: "ea-adeboye",
    name: "Pastor E.A. Adeboye",
    ministry: "Redeemed Christian Church of God",
    type: "Living teacher",
    status: "unverified",
    relationship: "Not yet affiliated with Sayved",
    image: "/assets/pastor_ita.jpg",
    topics: ["Holiness", "Prayer", "Wisdom", "Family"],
    officialSources: ["RCCG official channels", "Open Heavens public routes", "Official sermon routes"],
    canDeepRag: false,
  },
  {
    id: "benson-idahosa",
    name: "Archbishop Benson Idahosa",
    ministry: "Church of God Mission International",
    type: "Estate",
    status: "estate",
    relationship: "Estate - official sources only",
    image: "/assets/pastor_ita.jpg",
    topics: ["Faith", "Leadership", "Evangelism", "Courage"],
    officialSources: ["Official ministry routes", "Estate-approved public materials", "Legacy library routes"],
    canDeepRag: false,
  },
];

export const pastors = teachers;
