export const teachers = [
  {
    id: "tb-joshua",
    name: "Prophet T.B. Joshua",
    ministry: "The Synagogue, Church Of All Nations",
    type: "Estate",
    status: "estate",
    relationship: "Estate - official sources only",
    image: "/assets/TB Joshua.jpeg",
    topics: ["Faith", "Healing", "Prayer", "Hope"],
    officialSources: [
      { label: "Official SCOAN channel", verified: false, url: null },
      { label: "SCOAN sermon library", verified: false, url: null },
      { label: "Emmanuel TV public routes", verified: false, url: null },
    ],
    canDeepRag: false,
  },
  {
    id: "pastor-chris",
    name: "Pastor Chris Oyakhilome",
    ministry: "LoveWorld Incorporated / Christ Embassy",
    type: "Living teacher",
    status: "unverified",
    relationship: "Not yet affiliated with Sayved",
    image: "/assets/Chris Oyakhilome.jpeg",
    topics: ["Faith", "Confession", "Healing", "Prayer"],
    officialSources: [
      { label: "LoveWorld official platforms", verified: false, url: null },
      { label: "Rhapsody public routes", verified: false, url: null },
      { label: "Official YouTube route", verified: false, url: null },
    ],
    canDeepRag: false,
  },
  {
    id: "ea-adeboye",
    name: "Pastor E.A. Adeboye",
    ministry: "Redeemed Christian Church of God",
    type: "Living teacher",
    status: "unverified",
    relationship: "Not yet affiliated with Sayved",
    image: "/assets/Pastor Enoch Adejare Adeboye .jpeg",
    topics: ["Holiness", "Prayer", "Wisdom", "Family"],
    officialSources: [
      { label: "RCCG official channels", verified: false, url: null },
      { label: "Open Heavens public routes", verified: false, url: null },
      { label: "Official sermon routes", verified: false, url: null },
    ],
    canDeepRag: false,
  },
  {
    id: "benson-idahosa",
    name: "Archbishop Benson Idahosa",
    ministry: "Church of God Mission International",
    type: "Estate",
    status: "estate",
    relationship: "Estate - official sources only",
    image: "/assets/Benson Idahosa.jpeg",
    topics: ["Faith", "Leadership", "Evangelism", "Courage"],
    officialSources: [
      { label: "Official ministry routes", verified: false, url: null },
      { label: "Estate-approved public materials", verified: false, url: null },
      { label: "Legacy library routes", verified: false, url: null },
    ],
    canDeepRag: false,
  },
];

export const pastors = teachers;
